[package]
name = "video-api"
version = "0.0.1"
edition = "2021"

[[bin]]
name = "video-api"
path = "src/main.rs"

[dependencies]
tokio = { version = "1.34.0", features = ["full"] }
tracing = "0.1.40"
anyhow = "1.0.75"
sqlx = { version = "0.7.2", features = ["postgres", "runtime-tokio", "tls-rustls", "json", "chrono", "uuid"] }
sqlx-postgres = "0.7.2"
tonic = { version = "0.10.2", features = ["tls"] }
prost = "0.12.1"
uuid = { version = "1.5.0", features = ["v4"] }
serde = { version = "1.0.192", features = ["derive"] }
chrono = { version = "0.4.31", default-features = false, features = ["serde", "clock"] }
tokio-stream = { version = "0.1.14", features = ["sync"] }
async-stream = "0.3.5"
futures = "0.3.29"
futures-util = "0.3.29"
bytes = "1.5.0"
async-graphql = { version = "6.0.10", default-features = false, features = ["dataloader"] }
async-trait = "0.1.74"
jwt = "0.16.0"
hmac = "0.12.1"
sha2 = "0.10.8"
rand = "0.8.5"
async-nats = "0.33.0"
ulid = "1.1.0"
hex = "0.4.3"
base64 = "0.21.5"
serde_json = "1.0.108"

common = { workspace = true, features = ["default"] }
config = { workspace = true }
pb = { workspace = true }
video-common = { workspace = true }
binary-helper = { workspace = true }