[package]
name = "video-api"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.32.0", features = ["full"] }
tracing = "0.1.37"
anyhow = "1.0.75"
sqlx = { version = "0.7.1", features = ["postgres", "runtime-tokio-native-tls", "json", "chrono", "uuid"] }
sqlx-postgres = "0.7.1"
tonic = { version = "0.10.1", features = ["tls"] }
prost = "0.12.1"
uuid = { version = "1.4.1", features = ["v4"] }
serde = { version = "1.0.188", features = ["derive"] }
chrono = { version = "0.4.31", default-features = false, features = ["serde", "clock"] }
tokio-stream = { version = "0.1.14", features = ["sync"] }
async-stream = "0.3.5"
futures = "0.3.28"
futures-util = "0.3.28"
bytes = "1.5.0"
async-graphql = { version = "6.0.7", default-features = false, features = ["dataloader"] }
async-trait = "0.1.73"
jwt = "0.16.0"
hmac = "0.12.1"
sha2 = "0.10.7"
rand = "0.8.5"
async-nats = "0.32.0"
ulid = "1.1.0"
hex = "0.4.3"
base64 = "0.21.4"
serde_json = "1.0.107"

common = { workspace = true, features = ["default"] }
config = { workspace = true }
pb = { workspace = true }
video-common = { workspace = true }
