[workspace]

members = [
    "backend/api",
    "frontend/player",
    "video/edge",
    "video/ingest",
    "video/transcoder",
    "common",
]

# We don't want to build the wasm by default, this is because its built by a yarn script
default-members = [
    "backend/api",
    "video/edge",
    "video/ingest",
    "video/transcoder",
    "common",
]

[profile.release.package.player]
opt-level = "s"
