[package]
name = "video-player-types"
version = "0.0.1"
edition = "2021"

[dependencies]
serde = { version = "1.0.188", features = ["derive"] }
ulid = { version = "1.1.0", default-features = false }
url = { version = "2.4.1", default-features = false, features = ["serde"] }
