[advisories]
ignore = []
informational_warnings = ["unmaintained"]
severity_threshold = "low"

[database]
path = "~/.cargo/advisory-db" # Path where advisory git repo will be cloned
url = "https://github.com/RustSec/advisory-db.git" # URL to git repo
fetch = true
stale = false

[output]
deny = ["unmaintained"] 
format = "terminal"
quiet = false 
show_tree = true

[target]
arch = "x86_64"
os = "linux"

[yanked]
enabled = true
update_index = true
