[profile.default]
test-threads = "num-cpus"
slow-timeout = { period = "10s", terminate-after = 3 }

[profile.ci]
test-threads = "num-cpus"
slow-timeout = { period = "10s", terminate-after = 20 }
retries = { backoff = "exponential", count = 5, delay = "2s", jitter = true }

[test-groups]
serial = { max-threads = 1 }

[[profile.default.overrides]]
filter = 'test(serial)'
test-group = 'serial'
