name: Lint, Test & Build

on:
  pull_request:
    branches:
      - main
      - feature/*
  push:
    branches:
      - main
      - feature/*

concurrency:
  group: lint-test-build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-test:
    name: Run Lint + Test
    runs-on: ubuntu-latest
    container: ghcr.io/scuffletv/build:1.67.1
    services:
      postgres:
        image: postgres:15.2
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432

    env:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/scuffle

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          cache: "yarn"
          node-version: 18

      - name: Set up cargo registry cache
        uses: actions/cache@v3
        continue-on-error: false
        with:
          path: |
            /usr/local/cargo/registry/index/
            /usr/local/cargo/registry/cache/
            /usr/local/cargo/git/db/
          key: gnu-rust-registry-${{ hashFiles('**/Cargo.lock', '**/Cargo.toml') }}
          restore-keys: |
            gnu-rust-registry-

      - name: Set up cargo target cache
        uses: actions/cache@v3
        continue-on-error: false
        with:
          path: |
            target/
          key: gnu-rust-target-lint-test-rust-${{ hashFiles('**/Cargo.lock', '**/Cargo.toml') }}
          restore-keys: |
            gnu-rust-target-lint-test-rust-

      - name: Install dependencies
        run: mask bootstrap --no-db --no-docker --no-env --no-stack --no-rust

      - name: Run migrations
        run: mask db migrate

      - name: Run Lint
        run: mask lint

      - name: Run Test Rust
        run: mask test --no-js

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: lcov.info
          fail_ci_if_error: true

      - name: Run Test JavaScript
        run: mask test --no-rust

  build:
    name: Run Build
    runs-on: ubuntu-latest
    container: ghcr.io/scuffletv/build:1.67.1
    needs: [lint-test]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          cache: "yarn"
          node-version: 18

      - name: Set up cargo registry cache
        uses: actions/cache@v3
        continue-on-error: false
        with:
          path: |
            /usr/local/cargo/registry/index/
            /usr/local/cargo/registry/cache/
            /usr/local/cargo/git/db/
          key: gnu-rust-registry-${{ hashFiles('**/Cargo.lock', '**/Cargo.toml') }}
          restore-keys: |
            gnu-rust-registry-

      - name: Set up cargo target cache
        uses: actions/cache@v3
        continue-on-error: false
        with:
          path: |
            target/
          key: gnu-rust-target-build-${{ hashFiles('**/Cargo.lock', '**/Cargo.toml') }}
          restore-keys: |
            gnu-rust-target-build-

      - name: Install dependencies
        run: mask bootstrap --no-db --no-docker --no-env --no-js-tests --no-stack --no-rust

      - name: Run Build
        run: mask build
